Repository AlimuratDinch/minicap, pull requests merged in 2025-01, with the labels that each got.

#30 chore: yml pipeline
  .eslintrc.js
  .github/workflows/ci-pipeline.yml
  components/HelloWave.tsx
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/components/ThemedText.tsx.html
  coverage/lcov-report/components/index.html
  coverage/lcov-report/constants/Colors.ts.html
  coverage/lcov-report/constants/index.html
  coverage/lcov-report/favicon.png
  coverage/lcov-report/hooks/index.html
  coverage/lcov-report/hooks/useColorScheme.ts.html
  coverage/lcov-report/hooks/useThemeColor.ts.html
  coverage/lcov-report/index.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov.info
  package-lock.json
  package.json
Labels: chore

#34 (GH-12) docs: add component diagram
  assets/documentation/Component Diagram.jpg
Labels: documentation

#33 (GH-10) Added User Persons in Documents Folder
  assets/Documents/User-Personas.pdf
Labels: documentation

#32 docs: add rationale for codebase, API and framework choices
  assets/documentation/codebase_rationale.md
Labels: documentation

#35 (GH-11) docs: UI Mockups Sprint 1
  UI_Mockups_Sprint1
Labels: documentation, UI

#36 (GH-12) docs: Added UML Domain Model Diagram
  assets/Documents/SP1_SOEN_390_UML_Domain_Model.drawio.png
  assets/Documents/SP1_SOEN_390_UML_Domain_Model.jpg
Labels: documentation

#38 docs: sprint 1 retrospective
  assets/documentation/retrospectives/sprint_1/Sprint_1_retrospective.pdf
Labels: documentation
