Repository AlimuratDinch/minicap, pull requests merged in 2025-02, with the labels that each got.

#44 (GH-6) feat: hover over the buildings to get the basic information
  application/app/SGW_Map.tsx
  application/app/lib/supabase.ts
  application/databases_csv/buildings.csv
  application/databases_csv/buildings_row_data.csv
  application/package-lock.json
  application/package.json
Labels: enhancement, feature

#45 (GH-6) feat: hover over the buildings to get the basic information continuation
  application/app/Loyola_Map.tsx
  application/app/SGW_Map.tsx
  application/databases_csv/buildings.csv
Labels: enhancement, feature

#63 (GH-21) docs: UI Mockups Sprint 2
  documents/sprint2/UI_Mockups_Sprint2
Labels: documentation, UI

#62 (GH-27) docs: Release 1 Report
  documents/releases/release1_report.pdf
Labels: documentation

#66 (GH-22) docs: automated System/UI pdf
  documents/sprint2/Automated System_UI tests.pdf
Labels: documentation

#65 (GH-25) docs: sprint_2_retrospective
  documents/sprint2/Sprint 2 retrospective.pdf
Labels: documentation

#96 (GH-94) (GH-95) feat: Leave Feedback
  application/app/index.tsx
  application/components/FeedbackPopUp.tsx
  application/components/__tests__/FeedbackPopUp.test.tsx
Labels: feature

#102 (GH-25) docs: Add SOEN 390 - Sprint 3 Retrospective.pdf
  documents/sprint3/SOEN 390 - Sprint 3 Retrospective.pdf
Labels: documentation
