Repository AlimuratDinch/minicap, pull requests merged in 2025-04, with the labels that each got.

#133 (GH-48) feat: Concordia shuttle tracking & information
  application/app/_layout.tsx
  application/app/application.tsx
  application/app/shuttleInfo.tsx
  application/app/shuttleMap.tsx
  application/components/__tests__/ApplicationTests.tsx
  application/components/__tests__/shuttleInfoTests.tsx
  application/components/__tests__/shuttleMapTests.tsx
  application/constants/shuttleSchedule.ts
Labels: test, feature

#141 perf: removing SonarQube insecurities and bugs addressing the technical debts
  application/app/CampusMap.tsx
  application/app/FloorMap.tsx
  application/app/application.tsx
  application/app/lib/supabase.ts
  application/app/schedule.tsx
  application/components/__tests__/CampusMap_test.tsx
Labels: performance

#142 docs: updated Sprint 5 Retrospective and added Sprint 6 Retrospective PDFs
  documents/sprint5/Sprint 5 Retrospective.pdf
  documents/sprint6/Sprint 6 Retrospective.pdf
Labels: documentation
