Repository AlimuratDinch/minicap, pull requests merged in 2025-03, with the labels that each got.

#99 (GH-73) (GH-72) (GH-70) (GH-69) feat: Login function and updated user routes, test, and index file
  backend/package.json
  backend/routes/function.js
  backend/routes/index.html
  backend/routes/listen.js
  backend/routes/userRoutes.js
  backend/server.js
  backend/test/test_routes/userRoutes.test.js
Labels: test, feature, sprint3

#109 (GH-108) feat: UI mockups for Sprint 3-4
  documents/sprint4/UI_mockups_Sprint3-4
Labels: UI

#110 refactor/removed_hardcoded_password
  backend/test/test_routes/userRoutes.test.js
Labels: refactor

#112 docs: sprint_4_retrospective
  documents/sprint4/SOEN 390 - Sprint 4 Retrospective.pdf
Labels: documentation

#114 test: clarity for usability testing
  application/app/index.tsx
  application/components/__tests__/IndexTests.tsx
  application/package-lock.json
  application/package.json
Labels: enhancement, test, sprint3

#121 Bug-Fix: Fixed Live user location bug
  application/app/CampusMap.tsx
  application/components/__tests__/CampusMap_test.tsx
  application/package-lock.json
  application/package.json
Labels: bug

#125 docs: sprint_5_retrospective
  backend/test/test_routes/userRoutes.test.js
  documents/sprint5/Sprint 5 Retrospective.pdf
Labels: documentation

#126 test: improve coverage
  application/components/MapComponent.tsx
  application/components/__tests__/SearchBarTests.tsx
  application/components/__tests__/googleSignInTests.tsx
  application/components/__tests__/scheduleTests.tsx
  application/components/__tests__/supabaseTests.tsx
  application/components/__tests__/useBuildingsTests.tsx
  application/package-lock.json
  application/package.json
Labels: test

#128 Refactor: Remove Unused Backend Code
  backend/.gitignore
  backend/package.json
  backend/routes/function.js
  backend/routes/index.html
  backend/routes/listen.js
  backend/routes/userRoutes.js
  backend/security/auth.cjs
  backend/security/jwtService.cjs
  backend/server.js
  backend/services/supabaseClient.js
  backend/test/test_routes/userRoutes.test.js
Labels: refactor

#124 (GH-115) feat: UI Navigation/Menus & Fixing schedule issues
  application/app/application.tsx
  application/app/index.tsx
  application/app/menu.tsx
  application/app/schedule.tsx
  application/assets/concordia-logo.jpg
  application/assets/events1.jpg
  application/assets/news1.jpg
  application/assets/news2.jpg
  application/components/__tests__/ApplicationTests.tsx
  application/components/__tests__/IndexTests.tsx
  application/components/__tests__/googleSignInTests.tsx
  application/components/googleSignIn.ts
Labels: feature
